Repository artsy/stitch, pull requests merged in 2019-02, with the labels that each got.

#56 Bump to styled-components@4.0.3
  package.json
  yarn.lock
Labels: Version: Major

#57 Add verbose flag to debug deploy
  .circleci/config.yml
Labels: Version: Patch

#58 Auto was failing because auto-release-cli was installed
  package.json
  yarn.lock
Labels: Version: Patch

#59 Remove auto verbose mode
  .circleci/config.yml
Labels: Version: Trivial

#61 Accept already rendered block content.
  src/__tests__/renderSwitch.test.js
  src/__tests__/renderTemplate.test.js
  src/__tests__/utils.test.js
  src/index.tsx
  src/renderSwitch.tsx
  src/renderTemplate.tsx
  src/utils.tsx
Labels: Version: Minor
